---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 1
  network:

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: nc_tools
    run_list:
      - recipe[nc_base::make_nc_base]
      - recipe[nc_tools::install_tools]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
