---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 1
  network:
   - ['private_network', ip: '10.1.1.45']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.4

suites:
  - name: nc_tools
    run_list:
#      - recipe[nc_base::do_prs]
      - recipe[nc_base::make_nc_base]
      - recipe[nc_tools::install_tools]
#      - recipe[nc_tools::install_gw_jdbc]
#      - recipe[nc_tools::install_gw_jdbc-reporting-scripts]
#      - recipe[nc_tools::install_gw_remedy]
#      - recipe[nc_tools::setup_gw_remedy]
#      - recipe[nc_tools::install_prb_mttrapd]
#      - recipe[nc_tools::install_prb_tivoli-eif]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
