---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 1
  network:
   - ['private_network', ip: '10.1.1.45']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.4

suites:
  - name: default
    run_list:
      - recipe[nc_tools::install_gw_remedy]
      - recipe[nc_tools::install_gw_jdbc]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
