name 'nc_tools'
maintainer 'Ed Overton'
maintainer_email 'infuse.1301@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures nc_tools'
long_description 'Installs/Configures nc_tools'
version '0.3.1'
chef_version '>= 13.0'
supports 'redhat'

issues_url 'https://github.com/emo3/nc_tools/issues'
source_url 'https://github.com/emo3/nc_tools'

depends 'nc_base'
depends 'server_utils'
